spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: ${SERVER_PORT:8080}
